spring:
  application:
    name: zuul-gateway
server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  prefix: /api
  routes:
    account:
      path: /hello/**
      serviceId: hello
ribbon:
  eureka:
    enabled: true